name: CI

on:
  pull_request:
    branches: [ master, beta, development, test ]
  push:
    branches: [ master, beta, development, test ]

permissions:
  contents: read

jobs:
  win:
    runs-on: windows-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@3155a141048f8f89c06b4cdae32e7853e97536bc # 0.13.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: ⬇️ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.24'

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 18.x #lts/*
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Build
        shell: cmd
        run: |
          cd ui\References\Windows
          build.bat

  linux:
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@3155a141048f8f89c06b4cdae32e7853e97536bc # 0.13.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.24'

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 18.x #lts/*
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Install deps
        run: sudo apt-get install rpm libiw-dev

      - uses: ruby/setup-ruby@19a43a6a2428d455dbd1b85344698725179c9d8c # v1.289.0
        with:
          ruby-version: 2.7
          bundler-cache: false

      - name: Install fpm
        run: |
          gem install dotenv -v 2.8.1
          gem install fpm

      - name: Build CLI
        run: |
          cd cli/References/Linux
          ./build.sh -v $(cat ../../../ui/package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')

      - name: Build UI
        run: |
          cd ui/References/Linux
          ./build.sh -v $(cat ../../package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')

  macos:
    runs-on: macos-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@3155a141048f8f89c06b4cdae32e7853e97536bc # 0.13.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.24'

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 18.x #lts/*
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Install deps
        run: brew install autoconf automake libtool

      - name: Build
        run: |
          cd ui/References/macOS
          ./build.sh -v $(cat ../../package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g') -c ${{ env.APPLE_DEVID_CERTIFICATE }}
        env:
          APPLE_DEVID_CERTIFICATE: ${{ secrets.APPLE_DEVID_CERTIFICATE || 'DUMMY' }}
