name: CI

on:
  pull_request:
    branches: [ master, beta, development, test ]
  push:
    branches: [ master, beta, development, test ]

permissions:
  contents: read

jobs:
  win:
    runs-on: windows-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: ⬇️ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.24'

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3.0.0

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 18.x #lts/*
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Build
        shell: cmd
        run: |
          cd ui\References\Windows
          build.bat

  linux:
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.24'

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 18.x #lts/*
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Install deps
        run: sudo apt-get install rpm libiw-dev

      - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          ruby-version: 2.7
          bundler-cache: false

      - name: Install fpm
        run: |
          gem install dotenv -v 2.8.1
          gem install fpm

      - name: Build CLI
        run: |
          cd cli/References/Linux
          ./build.sh -v $(cat ../../../ui/package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')

      - name: Build UI
        run: |
          cd ui/References/Linux
          ./build.sh -v $(cat ../../package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')

  macos:
    runs-on: macos-latest

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.24'

      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 18.x #lts/*
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Install deps
        run: brew install autoconf automake libtool

      - name: Build
        run: |
          cd ui/References/macOS
          ./build.sh -v $(cat ../../package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g') -c ${{ env.APPLE_DEVID_CERTIFICATE }}
        env:
          APPLE_DEVID_CERTIFICATE: ${{ secrets.APPLE_DEVID_CERTIFICATE || 'DUMMY' }}
