name: "Security Scan (gosec)"

on:
  pull_request:
    branches: [ master, beta, development, test ]
  push:
    branches: [ master, beta, development, test ]

permissions: read-all

jobs:
  testsLinux:
    name: Tests (runs on Linux)
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run Gosec Security Scanner
        uses: securego/gosec@9e75c0576c9878035d4221392108d458abe10fc3 # v2.28.0
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: '-exclude=G104,G307 -no-fail -fmt sarif -out results.sarif ./...'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
