# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark and close stale issues

on:
  schedule:
  - cron: '30 1 * * 2'  # Scheduled to run at 1:30 AM every Tuesday
  workflow_dispatch:    # Allows manual triggering of the workflow

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        days-before-pr-stale: 36500 # 100 years. PRs - effectively disabled. 
        
        operations-per-run: 330     # Increase max operations. 

        days-before-stale: 365      # 1 year
        days-before-close: 6        # Since the action scheduled to run once a week, we set this to 6 days to ensure it closes issues after 7 days of inactivity.

        stale-issue-message: |
            This issue has been automatically marked as inactive because it has not had activity in the past year.
            
            If no further activity occurs, this issue will be automatically closed in one week in order to increase our focus on active topics.

        close-issue-message: |
            This issue has been automatically closed because it has not had recent activity. Thank you for your contributions.

            If the issue has not been resolved, you can [find more information in our Help Center](https://www.ivpn.net/knowledgebase/general/).
        
        stale-issue-label: 'stale'

        exempt-all-milestones: true
        exempt-all-assignees: true
        exempt-issue-labels: 'never-stale'